language: generic

services:
  - docker

before_install:
  - docker pull hadolint/hadolint

script:
  - docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 - < 10/Dockerfile
  - docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 - < 10/slim/Dockerfile
  - docker run --rm -i hadolint/hadolint hadolint --ignore DL3018 - < 10/alpine/Dockerfile
  - docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 - < 12/Dockerfile
  - docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 - < 12/slim/Dockerfile
  - docker run --rm -i hadolint/hadolint hadolint --ignore DL3018 - < 12/alpine/Dockerfile
