name: Test Docker image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker run -i $(docker build -q 10) /bin/sh -c "node --version && google-chrome --version"
          docker run -i $(docker build -q 10/slim) /bin/sh -c "node --version && google-chrome --version"
          docker run -i $(docker build -q 10/alpine) /bin/sh -c "node --version && chromium-browser --version"
          docker run -i $(docker build -q 12) /bin/sh -c "node --version && google-chrome --version"
          docker run -i $(docker build -q 12/slim) /bin/sh -c "node --version && google-chrome --version"
          docker run -i $(docker build -q 12/alpine) /bin/sh -c "node --version && chromium-browser --version"
